import puppeteer from 'puppeteer';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import MarkdownIt from 'markdown-it';
import { UnifiedIndex, TopicNotes } from '../types/index.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export class PdfService {
  private md: MarkdownIt;
  private cssCache: string | null = null;

  constructor() {
    this.md = new MarkdownIt({ html: true, breaks: true });
    
    // Override table rendering to use template's .tbl class
    this.md.renderer.rules.table_open = () => '<table class="tbl">\n';
  }

  private escapeHtml(unsafe: string): string {
    return unsafe
         .replace(/&/g, "&amp;")
         .replace(/</g, "&lt;")
         .replace(/>/g, "&gt;")
         .replace(/"/g, "&quot;")
         .replace(/'/g, "&#039;");
  }

  private getCss(): string {
    if (!this.cssCache) {
      const cssPath = path.join(__dirname, 'pdf-template.css');
      this.cssCache = fs.readFileSync(cssPath, 'utf-8');
    }
    return this.cssCache;
  }

  public async generatePDF(index: UnifiedIndex, notesList: TopicNotes[]): Promise<Buffer> {
    const css = this.getCss();

    // Group notes by topicId for quick lookup
    const notesMap = new Map<string, TopicNotes>();
    for (const n of notesList) {
      notesMap.set(n.topicId, n);
    }

    let htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${index.title} · Notes</title>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&family=Syne:wght@400;500;600;700;800&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,400&display=swap" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', () => {
    mermaid.initialize({ startOnLoad: true, theme: 'default', securityLevel: 'loose' });
  });
</script>
<style>
${css}
</style>
</head>
<body>
`;

    // Cover Page
    htmlContent += `
<div class="page">
  <div class="run-head">
    <div class="run-head-left">
      <div class="run-chapter">NOTEFORGE</div>
      <div class="run-dot"></div>
      <div class="run-topic">AUTO-GENERATED LECTURE NOTES</div>
    </div>
  </div>
  <div class="accent-bar">
    <div class="ab-seg" style="background:var(--c-pink)"></div>
    <div class="ab-seg" style="background:var(--c-cyan)"></div>
    <div class="ab-seg" style="background:var(--c-lime)"></div>
    <div class="ab-seg" style="background:var(--c-purple)"></div>
    <div class="ab-seg" style="background:var(--c-amber)"></div>
    <div class="ab-seg" style="background:var(--c-teal)"></div>
  </div>
  <div class="content cover-body">
    <div class="chapter-eyebrow">PLAYLIST NOTES</div>
    <div class="chapter-title" style="font-size: 46px;">${index.title}</div>
    <div class="chapter-desc">These comprehensive study notes were automatically generated by NoteForge.</div>
  </div>
  <div class="run-foot">
    <div class="foot-tag">NOTEFORGE · ${new Date().getFullYear()}</div>
  </div>
</div>
`;

    // TOC Page
    htmlContent += `
<div class="page">
  <div class="run-head">
    <div class="run-head-left">
      <div class="run-chapter">NOTEFORGE</div>
      <div class="run-dot"></div>
      <div class="run-topic">TABLE OF CONTENTS</div>
    </div>
  </div>
  <div class="accent-bar">
    <div class="ab-seg" style="background:var(--c-pink)"></div>
    <div class="ab-seg" style="background:var(--c-cyan)"></div>
    <div class="ab-seg" style="background:var(--c-lime)"></div>
    <div class="ab-seg" style="background:var(--c-purple)"></div>
    <div class="ab-seg" style="background:var(--c-amber)"></div>
    <div class="ab-seg" style="background:var(--c-teal)"></div>
  </div>
  <div class="content">
    <div class="h-chap" style="margin-bottom: 20px;">Table of Contents</div>
    <div class="toc-grid">
`;

    // TOC Grid
    index.topics.forEach((topic, idx) => {
      htmlContent += `
      <div class="toc-item" style="page-break-inside: avoid; break-inside: avoid;">
        <div class="toc-num" style="background:var(--c-pink)">${(idx + 1).toString().padStart(2, '0')}</div>
        <div class="toc-text">
          <div class="toc-section">${topic.title}</div>
          <div class="toc-sub">Chapter ${idx + 1}</div>
        </div>
      </div>
      `;
    });

    htmlContent += `
    </div>
  </div>
</div>
`;

    // Notes Pages (One per topic)
    // To allow proper pagination for long notes, we don't force them into a single .page div with fixed height.
    // Instead, we create a continuous container that looks like a page, and let Puppeteer paginate it.
    // However, the template defines .page as fixed height.
    // We will override .page for the printable PDF so that it expands automatically and page breaks are handled.
    
    htmlContent += `<style>
      @media print {
        body { background: white; padding: 0; margin: 0; }
        .page { height: auto; min-height: 100vh; box-shadow: none; page-break-after: always; }
        .content { flex: none; height: auto; overflow: visible; }
        .run-head, .accent-bar, .run-foot { display: none; } /* Alternatively, we can use CSS page margins for headers/footers */
      }
      .auto-page { width: var(--pw); background: var(--surface); box-shadow: 0 6px 48px rgba(0,0,0,.22); margin-bottom: 28px; display: flex; flex-direction: column; page-break-after: always; }
      @media print { .auto-page { width: 100%; box-shadow: none; margin-bottom: 0; } }
    </style>`;

    index.topics.forEach((topic, idx) => {
      const notes = notesMap.get(topic.id);
      if (!notes) return;

      const buildContentFromSections = (note: TopicNotes): string => {
        if (!note.sections?.length) return note.summary ? `<p class="body-text">${this.md.renderInline(note.summary)}</p>` : '';
        return note.sections.map((s: any) => {
          if (s.type === 'heading') {
            const level = s.level || 2;
            if (level === 2) {
              return `<div class="h-sec"><div class="h-sec-text">${this.escapeHtml(s.content)}</div></div>`;
            } else if (level === 3) {
              return `<div class="h-sub"><div class="h-sub-mark bg-primary"></div><div class="h-sub-text">${this.escapeHtml(s.content)}</div></div>`;
            } else {
              return `<div class="h-topic"><div class="h-topic-text">${this.escapeHtml(s.content)}</div><div class="h-topic-line"></div></div>`;
            }
          }
          if (s.type === 'code') {
            const lang = s.codeSnippet?.language || 'text';
            const code = s.codeSnippet?.code || s.content;
            return `
              <div class="code-block">
                <div class="code-topbar">
                  <div class="code-dots">
                    <div class="code-dot dot-r"></div><div class="code-dot dot-y"></div><div class="code-dot dot-g"></div>
                  </div>
                  <div class="code-lang">${lang}</div>
                </div>
                <div class="code-body">
                  <pre><code>${this.escapeHtml(code)}</code></pre>
                </div>
              </div>
            `;
          }
          if (s.type === 'mermaid') {
            const code = s.diagram?.code || s.content || '';
            const cleanCode = code.replace(/^```mermaid\n?/, '').replace(/\n?```$/, '').trim();
            return `
              <div class="mermaid-container" style="display:flex; justify-content:center; margin: 16px 0;">
                <div class="mermaid">${this.escapeHtml(cleanCode)}</div>
              </div>
            `;
          }
          if (s.type === 'bullets') {
             const items = s.items?.map((i: string) => `<li><div class="nb-dot" style="background:var(--ink-4)"></div><div>${this.md.renderInline(i)}</div></li>`).join('') || '';
             return `<ul class="nb">${items}</ul>`;
          }
          if (s.type === 'numbered') {
             const items = s.items?.map((i: string) => `<li><div>${this.md.renderInline(i)}</div></li>`).join('') || '';
             return `<ol class="nn">${items}</ol>`;
          }
          if (s.type === 'quote' || s.type === 'special') {
             const typeRaw = s.specialNote?.type || 'info';
             const typeClass = typeRaw === 'warning' ? 'warn' : typeRaw === 'caution' ? 'danger' : typeRaw === 'important' ? 'ok' : typeRaw === 'tip' ? 'tip' : 'info';
             const typeText = typeRaw.toUpperCase();
             const mdContent = this.md.renderInline(s.specialNote?.content || s.content);
             
             return `
               <div class="callout ${s.type === 'quote' ? 'quote' : typeClass}">
                 ${s.type !== 'quote' ? `<div class="callout-head">${typeText}</div>` : ''}
                 <div class="callout-body">${mdContent}</div>
               </div>
             `;
          }
          
          // Paragraph or mixed markdown content
          let html = this.md.render(s.content || '');
          // inject body-text class into p tags
          html = html.replace(/<p>/g, '<p class="body-text">');
          return html;
        }).join('\n');
      };

      let finalHtml = buildContentFromSections(notes);
      
      if (notes.keyTakeaways && notes.keyTakeaways.length > 0) {
        const takeawaysItems = notes.keyTakeaways.map(t => `<li><div class="nb-dot" style="background:var(--c-teal)"></div><div>${this.md.renderInline(t)}</div></li>`).join('');
        finalHtml += `
          <div class="callout ok">
            <div class="callout-head">KEY TAKEAWAYS</div>
            <ul class="nb" style="margin-left: 0;">${takeawaysItems}</ul>
          </div>
        `;
      }

      htmlContent += `
<div class="auto-page">
  <div class="run-head">
    <div class="run-head-left">
      <div class="run-chapter">CHAPTER ${(idx + 1).toString().padStart(2, '0')}</div>
      <div class="run-dot"></div>
      <div class="run-topic">${topic.title.toUpperCase()}</div>
    </div>
  </div>
  <div class="accent-bar">
    <div class="ab-seg" style="background:var(--c-pink)"></div>
    <div class="ab-seg" style="background:var(--c-cyan)"></div>
    <div class="ab-seg" style="background:var(--c-lime)"></div>
    <div class="ab-seg" style="background:var(--c-purple)"></div>
    <div class="ab-seg" style="background:var(--c-amber)"></div>
    <div class="ab-seg" style="background:var(--c-teal)"></div>
  </div>
  
  <div class="content">
    <div class="h-chap">
      <div class="chap-badge" style="background:var(--c-pink)">CH ${(idx + 1).toString().padStart(2, '0')}</div>
      ${topic.title}
    </div>
    <div class="h-chap-rule"></div>
    
    <div class="markdown-body">
      ${finalHtml}
    </div>
  </div>
</div>
`;
    });

    htmlContent += `
</body>
</html>
`;

    // Launch Puppeteer and generate PDF
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const page = await browser.newPage();
    
    // Set content and wait for web fonts to load
    await page.setContent(htmlContent, { waitUntil: 'load' });
    await page.evaluateHandle('document.fonts.ready');
    
    // Wait for Mermaid to process
    await page.waitForFunction(() => {
      const doc = (globalThis as any).document;
      if (!doc) return true;
      const mermaids = doc.querySelectorAll('.mermaid');
      if (mermaids.length === 0) return true;
      let allDone = true;
      mermaids.forEach((m: any) => {
        if (!m.querySelector('svg')) allDone = false;
      });
      return allDone;
    }, { timeout: 15000 }).catch(() => console.log('Mermaid render timeout'));
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="width: 100%; padding: 0 40px; display: flex; justify-content: space-between; align-items: flex-end; font-family: 'JetBrains Mono', monospace; font-size: 8px; color: #A0A0A0; text-transform: uppercase; letter-spacing: 0.1em; padding-bottom: 5px; border-bottom: 1px solid #EAEAEA;">
          <div>NOTEFORGE</div>
          <div>${index.title}</div>
        </div>
      `,
      footerTemplate: `
        <div style="width: 100%; padding: 0 40px; display: flex; justify-content: space-between; align-items: center; font-family: 'JetBrains Mono', monospace; font-size: 8px; color: #A0A0A0; text-transform: uppercase; letter-spacing: 0.1em;">
          <div>NOTEFORGE · ${index.title}</div>
          <div>Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
        </div>
      `,
      margin: {
        top: '60px',
        right: '0px',
        bottom: '50px',
        left: '0px'
      }
    });

    await browser.close();

    return Buffer.from(pdfBuffer);
  }
}

export const pdfService = new PdfService();
